version: "3.8"

services:
  test-manager:
    build:
      context: ./test-manager
      dockerfile: Dockerfile
    container_name: opensearch-test-manager
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=test-manager
    networks:
      - opensearch-loadtester-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  load-generator:
    build:
      context: ./load-generator
      dockerfile: Dockerfile
    container_name: opensearch-load-generator
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=load-generator
      - SERVER_PORT=8081
    networks:
      - opensearch-loadtester-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8081/actuator/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - test-manager

networks:
  opensearch-loadtester-network:
    driver: bridge
